#!/usr/bin/env python3
"""
llm_report_generator.py

Reads llm_summary_input.md files generated by spike_explainer.py,
sends the context to an LLM, and generates a final readable analytical 
report for each game.

Supports a flexible provider adapter architecture:
- Gemini
- OpenAI
- Anthropic Claude
- OpenAI-compatible (OpenRouter, Groq, Together, Ollama, LM Studio)
- Custom HTTP endpoints
"""

import argparse
import csv
import json
import logging
import os
import shutil
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Dict, Any, Optional

# --- Constants ---
DEFAULT_INPUT_DIR = "/content/drive/MyDrive/steam_diploma/data/spike_explainer"
DEFAULT_LIMIT = 10
DEFAULT_LANGUAGE = "ru"

# Mapping specific provider names to their default OpenAI-compatible base URLs
OAI_COMPATIBLE_DEFAULTS = {
    "openrouter": "https://openrouter.ai/api/v1",
    "groq": "https://api.groq.com/openai/v1",
    "together": "https://api.together.xyz/v1",
    "ollama": "http://localhost:11434/v1",
    "lmstudio": "http://localhost:1234/v1"
}

# --- Logging Setup ---
def setup_logging(input_dir: Path, dry_run: bool):
    input_dir.mkdir(parents=True, exist_ok=True)
    log_format = "%(asctime)s [%(levelname)s] %(message)s"
    logging.basicConfig(level=logging.INFO, format=log_format, datefmt="%Y-%m-%d %H:%M:%S")
    
    if not dry_run:
        file_handler = logging.FileHandler(input_dir / "llm_report_generator_errors.log")
        file_handler.setLevel(logging.WARNING)
        file_handler.setFormatter(logging.Formatter(log_format))
        logging.getLogger().addHandler(file_handler)

# --- Prompts ---
def get_prompt_instructions(language: str, game_title: str) -> str:
    if language.lower() == "en":
        return f"""You are a Steam game marketing analyst.
Analyze the provided data about a spike in Steam Top Wishlists.

Rules:
- Use ONLY facts from the provided file.
- Do not invent events, links, dates, or causes.
- Separate confirmed facts from hypotheses.
- If data is insufficient, state clearly that attribution is weak.
- Do not claim exact wishlist numbers if they are not in the data.
- Write clearly and structurally.

Generate a report in English with this structure:

# Spike Analysis: {game_title}

## 1. Executive Summary
2-4 sentences: what happened and how confidently the spike can be explained.

## 2. Rank Movement
Briefly describe the change in Steam Top Wishlists position.

## 3. Confirmed Facts
List of facts directly supported by the evidence.

## 4. Probable Causes
Explain the most likely causes, but do not present hypotheses as facts.

## 5. Weak Hypotheses & Uncertainties
What might have influenced it but is not well-supported by evidence.

## 6. Recommended Manual Checks
Which sources should be checked manually: YouTube, TikTok, Instagram, Reddit, X, Steam page, developer/publisher accounts.

## 7. Marketing Lesson
What practical takeaway a game developer can learn from this event.

---
RAW DATA FOR ANALYSIS:
"""
    else:
        return f"""Ты аналитик по маркетингу игр в Steam.
Проанализируй предоставленные данные о всплеске игры в Steam Top Wishlists.

Правила:
- Используй только факты из предоставленного файла.
- Не придумывай событий, ссылок, дат и причин.
- Разделяй подтверждённые факты и гипотезы.
- Если данных недостаточно, прямо скажи, что атрибуция слабая.
- Не утверждай точное количество вишлистов, если его нет в данных.
- Пиши ясно и структурно.

Сформируй отчёт на русском языке со структурой:

# Анализ всплеска: {game_title}

## 1. Краткий вывод
2–4 предложения: что произошло и насколько уверенно можно объяснить всплеск.

## 2. Движение в рейтинге
Кратко опиши изменение позиции Steam Top Wishlists.

## 3. Подтверждённые факты
Список фактов, которые прямо подтверждаются evidence.

## 4. Вероятные причины всплеска
Объясни наиболее вероятные причины, но не выдавай гипотезы за факты.

## 5. Слабые гипотезы и неопределённости
Что могло повлиять, но не подтверждено достаточно хорошо.

## 6. Что проверить вручную
Какие источники стоит проверить дополнительно: YouTube, TikTok, Instagram, Reddit, X, Steam page, developer/publisher accounts.

## 7. Маркетинговый урок
Какой практический вывод может сделать разработчик игры.

---
СЫРЫЕ ДАННЫЕ ДЛЯ АНАЛИЗА:
"""

# --- Provider Adapters ---
def generate_gemini(prompt: str, model: str, api_key: str, kwargs: dict) -> str:
    try:
        from google import genai
    except ImportError:
        raise ImportError("google-genai package is not installed. Run: pip install google-genai")
    
    client = genai.Client(api_key=api_key)
    
    config = {}
    if kwargs.get("temperature") is not None: config["temperature"] = kwargs["temperature"]
    if kwargs.get("max_tokens") is not None: config["max_output_tokens"] = kwargs["max_tokens"]
        
    response = client.models.generate_content(
        model=model or "gemini-2.5-flash",
        contents=prompt,
        config=config if config else None
    )
    return response.text

def generate_openai(prompt: str, model: str, api_key: str, kwargs: dict) -> str:
    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError("openai package is not installed. Run: pip install openai")
    
    client = OpenAI(api_key=api_key, timeout=kwargs.get("timeout_seconds", 60))
    
    params = {
        "model": model or "gpt-4o-mini",
        "messages": [{"role": "user", "content": prompt}],
    }
    if kwargs.get("temperature") is not None: params["temperature"] = kwargs["temperature"]
    if kwargs.get("max_tokens") is not None: params["max_tokens"] = kwargs["max_tokens"]
        
    response = client.chat.completions.create(**params)
    return response.choices[0].message.content

def generate_openai_compatible(prompt: str, model: str, api_key: str, base_url: str, kwargs: dict) -> str:
    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError("openai package is not installed. Run: pip install openai")
    
    client = OpenAI(api_key=api_key or "sk-dummy", base_url=base_url, timeout=kwargs.get("timeout_seconds", 60))
    
    params = {
        "model": model or "default-model",
        "messages": [{"role": "user", "content": prompt}],
    }
    if kwargs.get("temperature") is not None: params["temperature"] = kwargs["temperature"]
    if kwargs.get("max_tokens") is not None: params["max_tokens"] = kwargs["max_tokens"]
        
    response = client.chat.completions.create(**params)
    return response.choices[0].message.content

def generate_anthropic(prompt: str, model: str, api_key: str, kwargs: dict) -> str:
    try:
        from anthropic import Anthropic
    except ImportError:
        raise ImportError("anthropic package is not installed. Run: pip install anthropic")
    
    client = Anthropic(api_key=api_key, timeout=kwargs.get("timeout_seconds", 60))
    
    params = {
        "model": model or "claude-3-5-sonnet-latest",
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": kwargs.get("max_tokens") or 4000
    }
    if kwargs.get("temperature") is not None: params["temperature"] = kwargs["temperature"]
        
    response = client.messages.create(**params)
    return response.content[0].text

def generate_custom_http(prompt: str, model: str, endpoint: str, kwargs: dict) -> str:
    import requests
    
    headers = {"Content-Type": "application/json"}
    if kwargs.get("headers_json"):
        try:
            headers.update(json.loads(kwargs["headers_json"]))
        except json.JSONDecodeError as e:
            logging.error(f"Failed to parse custom headers JSON: {e}")
            
    payload = {
        "model": model,
        "prompt": prompt
    }
    if kwargs.get("temperature") is not None: payload["temperature"] = kwargs["temperature"]
    if kwargs.get("max_tokens") is not None: payload["max_tokens"] = kwargs["max_tokens"]
        
    response = requests.post(endpoint, headers=headers, json=payload, timeout=kwargs.get("timeout_seconds", 60))
    response.raise_for_status()
    
    data = response.json()
    
    if "choices" in data and isinstance(data["choices"], list) and len(data["choices"]) > 0:
        choice = data["choices"][0]
        if "message" in choice and "content" in choice["message"]: return choice["message"]["content"]
        if "text" in choice: return choice["text"]
    if "response" in data: return data["response"]
    
    return json.dumps(data)

# --- Dispatch Layer ---
def generate_with_provider(provider: str, prompt: str, model: str, api_key: str, **kwargs) -> tuple[str, float]:
    start_time = time.time()
    generated_text = ""
    
    provider_lower = provider.lower()
    
    if provider_lower == "gemini":
        generated_text = generate_gemini(prompt, model, api_key, kwargs)
    elif provider_lower == "openai":
        generated_text = generate_openai(prompt, model, api_key, kwargs)
    elif provider_lower == "anthropic":
        generated_text = generate_anthropic(prompt, model, api_key, kwargs)
    elif provider_lower in OAI_COMPATIBLE_DEFAULTS.keys() or provider_lower == "openai_compatible":
        base_url = kwargs.get("base_url") or OAI_COMPATIBLE_DEFAULTS.get(provider_lower)
        if not base_url: raise ValueError(f"Missing --base-url for OpenAI-compatible provider: {provider}")
        generated_text = generate_openai_compatible(prompt, model, api_key, base_url, kwargs)
    elif provider_lower == "custom_http":
        endpoint = kwargs.get("custom_endpoint") or kwargs.get("base_url")
        if not endpoint: raise ValueError("Missing --custom-endpoint for custom_http provider.")
        generated_text = generate_custom_http(prompt, model, endpoint, kwargs)
    else:
        raise ValueError(f"Unknown provider: {provider}")
        
    elapsed = round(time.time() - start_time, 2)
    return generated_text, elapsed

# --- Helpers ---
def extract_metadata(folder_path: Path) -> tuple[str, str]:
    game_title = "Unknown Game"
    appid = "Unknown AppID"
    
    meta_path = folder_path / "metadata.json"
    if meta_path.exists():
        try:
            with open(meta_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
                game_title = meta.get("game_title", game_title)
                appid = str(meta.get("appid", appid))
                return game_title, appid
        except Exception:
            pass
            
    parts = folder_path.name.split("__")
    for p in parts:
        if p.startswith("appid_"): appid = p.replace("appid_", "")
    if len(parts) >= 3:
        game_title = parts[2].replace("_", " ").title()
        
    return game_title, appid

def has_recent_run(llm_out_dir: Path, provider: str, model: str, max_age_hours: int = 12) -> bool:
    """Check if the exact same provider/model combo was generated very recently."""
    if not llm_out_dir.exists(): return False
    
    now = datetime.now(timezone.utc)
    for json_file in llm_out_dir.glob("*.json"):
        if json_file.name == "latest_summary.json": continue
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            
            # Check provider and model match
            if data.get("provider") == provider and data.get("model") == model:
                created = datetime.fromisoformat(data.get("created_at_utc"))
                if (now - created).total_seconds() < max_age_hours * 3600:
                    return True
        except Exception:
            pass
            
    return False

def append_to_index(index_path: Path, record: dict):
    fieldnames = [
        "created_at_utc", "timestamp", "appid", "game_title", "provider", "model", 
        "status", "folder_path", "input_file", "output_path", "error",
        "duration_sec", "response_length"
    ]
    file_exists = index_path.exists()
    with open(index_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        if not file_exists:
            writer.writeheader()
        writer.writerow(record)

# --- Main Execution ---
def main():
    parser = argparse.ArgumentParser(description="Generate LLM Analytical Reports for Steam Spikes.")
    parser.add_argument("--config-file", type=str, help="JSON configuration file overriding CLI arguments.")
    parser.add_argument("--input-dir", type=str, default=DEFAULT_INPUT_DIR, help="Base directory for recursive search and master index.")
    parser.add_argument("--input-folder", type=str, help="Process a single specific game folder (ignores recursive search).")
    parser.add_argument("--input-file", type=str, help="Process a single specific llm_summary_input.md file (ignores recursive search).")
    
    parser.add_argument("--provider", type=str, default="none", help="Provider (e.g. none, gemini, openai, anthropic, ollama, openrouter, custom_http)")
    parser.add_argument("--model", type=str, help="Model to use (defaults depend on provider).")
    parser.add_argument("--api-key", type=str, help="Explicit API key.")
    parser.add_argument("--api-key-env", type=str, help="Environment variable name for API key.")
    parser.add_argument("--base-url", type=str, help="Base URL for OpenAI-compatible APIs.")
    parser.add_argument("--custom-endpoint", type=str, help="Endpoint for custom HTTP API.")
    parser.add_argument("--headers-json", type=str, help="Custom headers in JSON format for custom_http.")
    parser.add_argument("--temperature", type=float, help="Temperature for generation.")
    parser.add_argument("--max-tokens", type=int, help="Maximum tokens to generate.")
    parser.add_argument("--timeout-seconds", type=int, default=60, help="Request timeout.")
    parser.add_argument("--limit", type=int, default=DEFAULT_LIMIT, help="Max folders to process (recursive mode only).")
    parser.add_argument("--overwrite", action="store_true", help="Force overwrite even if exact file exists or recent run exists.")
    parser.add_argument("--dry-run", action="store_true", help="Print actions without modifying files/calling APIs.")
    parser.add_argument("--language", type=str, choices=["ru", "en"], default=DEFAULT_LANGUAGE)
    args = parser.parse_args()

    if args.config_file and Path(args.config_file).exists():
        with open(args.config_file, "r") as f:
            config = json.load(f)
            if "llm" in config:
                for k, v in config["llm"].items():
                    if hasattr(args, k) and v is not None: setattr(args, k, v)

    input_dir = Path(args.input_dir)
    setup_logging(input_dir, args.dry_run)
    index_path = input_dir / "llm_reports_index.csv"

    logging.info(f"Starting LLM Report Generator (Provider: {args.provider})")

    api_key = args.api_key
    if not api_key and args.api_key_env: api_key = os.environ.get(args.api_key_env)
    
    if args.provider == "gemini" and not api_key: api_key = os.environ.get("GEMINI_API_KEY")
    if args.provider == "openai" and not api_key: api_key = os.environ.get("OPENAI_API_KEY")
    if args.provider == "anthropic" and not api_key: api_key = os.environ.get("ANTHROPIC_API_KEY")

    kwargs = {
        "base_url": args.base_url, "custom_endpoint": args.custom_endpoint,
        "headers_json": args.headers_json, "temperature": args.temperature,
        "max_tokens": args.max_tokens, "timeout_seconds": args.timeout_seconds
    }

    raw_folders = []
    
    if args.input_file:
        logging.info("[MODE] single file")
        input_file_path = Path(args.input_file)
        if not input_file_path.exists() or not input_file_path.is_file():
            logging.error(f"Input file not found: {input_file_path}")
            sys.exit(1)
        raw_folders = [input_file_path.parent]
        
    elif args.input_folder:
        logging.info("[MODE] single folder")
        input_folder_path = Path(args.input_folder)
        target_file = input_folder_path / "llm_summary_input.md"
        if not target_file.exists():
            logging.error(f"llm_summary_input.md not found in folder: {input_folder_path}")
            sys.exit(1)
        raw_folders = [input_folder_path]
        
    else:
        logging.info("[MODE] recursive batch scan")
        logging.info(f"Scanning {input_dir} for llm_summary_input.md files...")
        all_inputs = list(input_dir.rglob("llm_summary_input.md"))
        raw_folders = [md_file.parent for md_file in all_inputs]
        raw_folders.sort(key=lambda x: x.stat().st_mtime, reverse=True)

    # Establish global run timestamp for this execution
    run_timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    folders_to_process = []
    for folder in raw_folders:
        llm_out_dir = folder / "llm_outputs"
        
        target_md = llm_out_dir / f"{args.provider}_{run_timestamp}.md"
        
        # Check strict overwrite rule for this exact run timestamp
        if target_md.exists() and not args.overwrite:
            logging.info(f"Skipping {folder.name} (exact file {target_md.name} exists).")
            continue
            
        # Check if recently processed by same provider/model
        if not args.overwrite and has_recent_run(llm_out_dir, args.provider, args.model):
            logging.info(f"Skipping {folder.name} (recent run detected for provider={args.provider} model={args.model}).")
            continue
            
        folders_to_process.append(folder)

    if not args.input_file and not args.input_folder:
        folders_to_process = folders_to_process[:args.limit]

    logging.info(f"Found {len(folders_to_process)} valid targets to process.")

    processed_count = 0
    error_count = 0

    for folder in folders_to_process:
        input_file = folder / "llm_summary_input.md"
        human_summary = folder / "human_summary.md"
        
        llm_out_dir = folder / "llm_outputs"
        if not args.dry_run:
            llm_out_dir.mkdir(parents=True, exist_ok=True)
            
        output_file_md = llm_out_dir / f"{args.provider}_{run_timestamp}.md"
        output_file_json = llm_out_dir / f"{args.provider}_{run_timestamp}.json"
        
        latest_md = llm_out_dir / "latest_summary.md"
        latest_json = llm_out_dir / "latest_summary.json"

        game_title, appid = extract_metadata(folder)
        logging.info(f"Processing: [{appid}] {game_title}")

        if args.dry_run:
            logging.info(f"[DRY-RUN] Would process {folder.name} -> {output_file_md.name}")
            continue

        status = ""
        error_msg = None
        generated_text = ""
        duration = 0.0
        now_utc = datetime.now(timezone.utc).isoformat()

        try:
            with open(input_file, "r", encoding="utf-8") as f:
                raw_input_text = f.read()

            if args.provider == "none":
                status = "draft_no_provider"
                if human_summary.exists():
                    with open(human_summary, "r", encoding="utf-8") as hf:
                        generated_text = f"# DRAFT REPORT — NO LLM PROVIDER USED\n\n{hf.read()}"
                else:
                    generated_text = f"# DRAFT REPORT — NO LLM PROVIDER USED\n\nAnalysis for {game_title}. No LLM provider was configured."
            else:
                if not api_key and args.provider in ["gemini", "openai", "anthropic"]:
                    status = "error_no_api_key"
                    error_msg = f"Missing API key for provider {args.provider}"
                    logging.warning(error_msg)
                else:
                    instruction = get_prompt_instructions(args.language, game_title)
                    full_prompt = f"{instruction}\n\n{raw_input_text}"

                    logging.info(f"Sending request to provider: {args.provider}")
                    generated_text, duration = generate_with_provider(
                        provider=args.provider, prompt=full_prompt, model=args.model, api_key=api_key, **kwargs
                    )
                    status = "success"
                    logging.info(f"Response received. Length: {len(generated_text)} chars. Time: {duration}s")

        except Exception as e:
            error_msg = str(e)
            status = "error_api_failure"
            logging.error(f"Failed to process {folder.name}: {e}")
            error_count += 1

        if generated_text:
            with open(output_file_md, "w", encoding="utf-8") as f:
                f.write(generated_text)
            shutil.copy2(output_file_md, latest_md)
            logging.info(f"[GENERATED] {output_file_md}")

        json_record = {
            "status": status, "provider": args.provider, "model": args.model, "base_url": args.base_url,
            "created_at_utc": now_utc, "timestamp": run_timestamp,
            "input_file": str(input_file), "output_path": str(output_file_md) if generated_text else "",
            "game_title": game_title, "appid": appid,
            "duration_sec": duration, "response_length": len(generated_text), "error": error_msg
        }
        
        with open(output_file_json, "w", encoding="utf-8") as f:
            json.dump(json_record, f, indent=4)
        shutil.copy2(output_file_json, latest_json)

        json_record["folder_path"] = str(folder)
        append_to_index(index_path, json_record)

        processed_count += 1

    logging.info(f"Finished. Processed: {processed_count} | Errors: {error_count}")

if __name__ == "__main__":
    main()